services:
  upload-service:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgres'
    volumes:
      - type: bind
        source: ./uploaded_documents
        target: /uploaded_documents
    ports:
      - "80:80"
    # Note that you will need to expose the port your server is running on here.
    # For reference: https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/#use-docker-compose..

  postgres:
    image: 'postgres:17.0-alpine'
    environment:
      - 'POSTGRES_USER=upload-service'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=main'
    volumes:
      - 'pg-data:/var/lib/postgresql/data'

  minio:
    image: 'quay.io/minio/minio:latest'
    command:
      - 'server'
      - '/mnt/data'
      - '--console-address'
      - ':9090'
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=password'
    ports:
      - '9090:9090'
    volumes:
      - 'minio-data:/mnt/data'

volumes:
  pg-data: {}
  minio-data: {}
