services:
  upload-service:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "80:80"

  postgres:
    image: 'postgres:17.0-alpine'
    environment:
      - 'POSTGRES_USER=upload-service'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=main'
    volumes:
      - 'pg-data:/var/lib/postgresql/data'

  minio:
    image: 'quay.io/minio/minio:latest'
    command:
      - 'server'
      - '/mnt/data'
      - '--console-address'
      - ':9090'
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=password'
    ports:
      - '9090:9090'
    volumes:
      - 'minio-data:/mnt/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data: {}
  minio-data: {}